export const dummyBanks = [
  { label: "Access Bank", value: "044" },
  { label: "Citibank Nigeria", value: "023" },
  { label: "Ecobank Nigeria", value: "050" },
  { label: "Fidelity Bank", value: "070" },
  { label: "First Bank of Nigeria", value: "011" },
  { label: "First City Monument Bank (FCMB)", value: "214" },
  { label: "Globus Bank", value: "00103" },
  { label: "Guaranty Trust Bank (GTB)", value: "058" },
  { label: "Heritage Bank", value: "030" },
  { label: "Jaiz Bank", value: "301" },
  { label: "Keystone Bank", value: "082" },
  { label: "Kuda Bank", value: "50211" },
  { label: "Opay", value: "100002" },
  { label: "Palmpay", value: "100033" },
  { label: "Parallex Bank", value: "104" },
  { label: "Polaris Bank", value: "076" },
  { label: "PremiumTrust Bank", value: "105" },
  { label: "Providus Bank", value: "101" },
  { label: "Stanbic IBTC Bank", value: "221" },
  { label: "Standard Chartered Bank Nigeria", value: "068" },
  { label: "Sterling Bank", value: "232" },
  { label: "Suntrust Bank", value: "100" },
  { label: "TAJ Bank", value: "302" },
  { label: "Titan Trust Bank", value: "102" },
  { label: "Union Bank of Nigeria", value: "032" },
  { label: "United Bank for Africa (UBA)", value: "033" },
  { label: "Unity Bank", value: "215" },
  { label: "Wema Bank", value: "035" },
  { label: "Zenith Bank", value: "057" },
]
